name: Revenuecat Auto Sync

on:
  schedule:
    - cron: "0 */2 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Files
        run: |
          curl -L \
            https://raw.githubusercontent.com/chxm1023/Rewrite/main/Reheji.js \
            -o Revenuecat.js

          curl -L \
            https://raw.githubusercontent.com/chxm1023/Rewrite/main/iTunes.js \
            -o iTunes.js         

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add Revenuecat.js
          git add iTunes.js

          git diff --cached --quiet && exit 0

          git commit -m "auto: sync js files"
          git push
